/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "boost_control.h"

volatile uint32_t heartbeat = 0;
volatile BoostOutput boost_status;

#define BOOST_POWER_STAGE_ARMED 0

static BoostController boost_controller;

/*
 * Call this from the future 20 kHz timer/ADC interrupt after converting the
 * ADC readings to volts, amperes, and degrees Celsius.
 */
void Boost_ControlTick20kHz(const BoostMeasurements *measurements)
{
    const BoostOutput output = Boost_Step(&boost_controller, measurements);

    boost_status = output;

    /*
     * Hardware adapter goes here:
     *   1. Disable TIM1/HRTIM immediately when output.pwm_enabled is false.
     *   2. Otherwise write output.duty to the timer compare register.
     * Keep a comparator/BKIN path for cycle-by-cycle overcurrent protection.
     */
}

static void Boost_Configure(void)
{
    BoostConfig config = Boost_ConfigSafeDefaults();

    /*
     * Example values only. Replace them after measuring the real divider,
     * shunt amplifier, inductor, MOSFET, diode, load, and switching stage.
     */
    config.control_period_s = 1.0f / 20000.0f;
    config.target_output_v = 24.0f;
    config.input_uvlo_v = 7.0f;
    config.output_ovp_v = 27.0f;
    config.current_limit_a = 4.0f;
    config.temperature_limit_c = 90.0f;
    config.minimum_duty = 0.02f;
    config.maximum_duty = 0.80f;
    config.duty_slew_rate_per_s = 2.0f;
    config.soft_start_time_s = 0.50f;
    config.proportional_gain = 0.015f;
    config.integral_gain_per_s = 2.0f;

    Boost_Init(&boost_controller, &config);

#if BOOST_POWER_STAGE_ARMED
    (void)Boost_Start(&boost_controller);
#endif

    boost_status = Boost_GetOutput(&boost_controller);
}

int main(void)
{
    Boost_Configure();

    for (;;)
    {
        heartbeat++;
    }
}
